--- #YAML:1.0
name:               Regexp-Parser
version:            0.20_01
abstract:           base class for parsing regexes
author:
    - Jeff japhy Pinyan <japhy@perlmonk.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Test::More:  0
resources:
    homepage:    http://wiki.github.com/toddr/Regexp-Parser
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/toddr/Regexp-Parser/tree/master
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
